services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -inMemory"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
    restart: unless-stopped

  init-dynamo-table:
    image: amazon/aws-cli
    restart: on-failure
    depends_on:
      - dynamodb-local
    command: dynamodb create-table --table-name reminders-dev-data --attribute-definitions AttributeName=pk,AttributeType=S AttributeName=sk,AttributeType=S --key-schema AttributeName=pk,KeyType=HASH AttributeName=sk,KeyType=RANGE --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --endpoint-url http://dynamodb-local:8000
    links:
      - dynamodb-local
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: local-key
      AWS_SECRET_ACCESS_KEY: local-secret
